### ISSUE TITLE
기본캘린더 형식의 달력 추가를 손쉽게 하는 기능

### ISSUE THREAD

**Issue by PsPLoG** [boostcampwm-2021/android01-CalendaRun#209]
## 진행 상황(option)
- [x] 기본캘린더 형식의 달력도 사용자가 쉽게 추가할 수 있는 UX필요

**Comment by simeunseok** [comment]
지금 같은 경우에서는 체크 포인트를 입력하지 않으면 기본 캘린더를 만들 수 있다는 것을 알려주면 좋겠네요~
