### ISSUE TITLE
키보드 입력창 사라지지 않음

### ISSUE THREAD

**Issue by Cha-Ji** [boostcampwm-2021/android01-CalendaRun#224]
Given 달력 관리 -> 달력 수정에서 달력 이름을 입력하기 위해 editText에 focus가 있는 상태
When 저장 버튼을 클릭해 달력 관리 페이지로 이동할 때
  And 앱바의 뒤로가기 버튼을 클릭해 원래 달력으로 돌아갈 때
Then 아직도 키보드가 켜져있음

<img src = "https://user-images.githubusercontent.com/55696672/142817870-d2b7e935-2e4c-4ee1-a08c-708c393716d9.png" width = 350 />

**Comment by shshksh** [comment]
저는 달력 관리 페이지에서 앱바로 뒤로갈때는 키보드가 정상적으로 사라지네요

**Comment by Cha-Ji** [comment]
간만에 찌그러진 월달력
<img src = "https://user-images.githubusercontent.com/55696672/142822013-1bc4b422-6d24-45ca-96be-c88019b1ece2.png" width = 350 />

**Comment by simeunseok** [comment]
사진이 너무 커요 조절 좀 해주세요 ㅋㅋㅋ

**Comment by Cha-Ji** [comment]
바~로 축소
