### ISSUE TITLE
달력 수정 페이지 버그

### ISSUE THREAD

**Issue by shshksh** [boostcampwm-2021/android01-CalendaRun#227]
![Screen_Recording_20211122-163410_One UI Home_1](https://user-images.githubusercontent.com/52354794/142821342-9f627300-8403-469c-8070-224a33bece17.gif)

1. 달력 수정 페이지로 진입 시 슬라이스가 보이지 않음
2. 저장 버튼 클릭 시 크래시

**Comment by simeunseok** [comment]
확인했습니다.

**Comment by simeunseok** [comment]
수정했으니 닫겠습니다~
