### ISSUE TITLE
연달력 ViewModel 문제

### ISSUE THREAD

**Issue by Cha-Ji** [boostcampwm-2021/android01-CalendaRun#296]
코딩하고 있는건 아니고 기술 정리를 하다보니 질문이 생겨서..ㅎㅎ

### 요약
- 현재 ViewModel의 기능은 schedule, design, clickedDay 등의 변수를 갖고 set, get 함수로 가득함.
- viewModel을 사용할 이유가 없음 뭘로 바꿀까
- composable함수는 상태유지가 되는데 viewModel은 상태유지가 안되는 것에 대한 해결방안

## ViewModel 사용이유
- 기존 사용이유는 xml이 사라진 만큼 더 view에 몰린 로직을 분리
- 그렇다면 viewModel일 이유가 없어 이름만 viewModel인 상태로 뒀음. (네이밍 변경 필요)

### 전제
- compose에는 다른 화면을 다녀와도 상태를 저장하는 rememberSaveable 태그가 존재함. (다른 activity를 다녀올 때에는 저장 안됨)
- 하지만 viewModel은 상태가 아니기 때문에 해당 태그를 사용할 수 없음.
```kotlin
// viewModel
val clickDay: State<LocalDateTime> = _clickDay
```

```kotlin
// view
val clickDay by rememberSaveable { viewModel.clickDay }
```
처럼 사용중
### 문제 상황
- 뷰가 재생성될 때 viewModel이 새로 생겨나고 새로 생겨난 viewModel의 clickDay에 따라 클릭테두리를 보여줌. 
- 상태유지를 시도하니 click을 하면 이전 뷰모델의 clickDay가 바뀌어서 화면에 반영이 안됨. 
- 추가적으로 현재 viewModel은 최상단 파일에서 선언 후 매개변수로 내려내려가는 상황. (가독성만을 위해 뷰 파일을 여러개로 나눈 상황)

### 결론
- 싱글톤으로 사용할까
  - 너무 찜찜함. 검색화면이나 일정 추가화면에서도 메모리를 잡아먹고 있을까?
- viewModel을 State객체로 만들까
  - 하지만 Schedule 관리나 designObj에 관한 기능을 월달력이랑 통합할 수 있는 여지를 아예 없앰.

ViewModel을 State 객체로 만드는 쪽으로 생각 중인데, 
멘토님이 뷰모델보다는 레포지토리로 만드는게 어떻냐는 말씀도 했었고, 혹시 다른 생각이 있으실까 해서 물어봅니다.

**Comment by simeunseok** [comment]
답변까진 아니지만 레포지토리로 만드는게 결국  싱글톤으로 활용하는거 아닌가요??

**Comment by Cha-Ji** [comment]
> 답변까진 아니지만 레포지토리로 만드는게 결국 싱글톤으로 활용하는거 아닌가요??

레포지토리를 일반 class로 두고 뷰가 생성될 때 같이 생성해서 쓸 수도 있지 않을까요?
싱글톤으로 사용하게 되면 라이브러리를 참조하는 순간부터 메모리를 차지하게 될 것 같아 찜찜했어요.

**Comment by simeunseok** [comment]
뷰가 생성될 때 같이 생성하는 거면 Hilt로 주입해주는 방식으로 해도 될거같네요!

**Comment by Cha-Ji** [comment]
ViewModel의 로직을 View로 이동시키니까 해결이 되네요... 그냥 view 코드를 다른 파일로 분리시킬 필요가 없는걸지도 모르겠네요 허허

제가 발생한 문제는 View가 재생성 될 때 자원을 그대로 재활용해서 재생성된 ViewModel이 아닌 이전 ViewModel을 참조하게되는 문제인데,
hilt로 주입시키면 View가 재생성되어도 ViewModel객체가 재생성 되지 않고 재활용되나요?
