### ISSUE TITLE
공휴일 불러오는 기능 문제 정리

### ISSUE THREAD

**Issue by simeunseok** [boostcampwm-2021/android01-CalendaRun#299]
공휴일 API를 Retrofit으로 가져오는 것은 문제되지 않는다. 하지만 이후 다음과 같은 고민이 생겼다.

- 앱을 시작할 때마다 공휴일 정보를 Retrofit으로 가져오기에는 공휴일 정보는 쉽게 바뀌지 않음
- 공휴일 정보를 내부에 저장해두는 것은 리스크가 있음 (공휴일이 간혹가다 추가되거나 삭제되는 일이 있을 수 있음 ex: 제헌절, 한글날)

위 문제를 해결하기위해 remote에서 받아오는 데이터를 local에 캐싱하면 좋겠다는 생각이 든다. 
그럼 다음과 같은 시나리오를 생각할 수 있다.

1. 달력을 불러올 때, 캐싱되어있는 데이터를 먼저 찾음
2. 캐싱되어있다면 데이터를 가져오고 remote로부터 새로 갱신된 값이 있는지 확인 후 다시 캐싱
3. 캐싱되어있지않다면 remote에서 데이터를 가져오고 캐싱

위와 같은 시나리오를 통해 데이터를 불러오면 좋겠지만, 역시 염려되는 문제가 있다.

- 어디에 캐싱할 것인가
- 공휴일 정보를 어디까지 캐싱해둘 것인가
- 캐싱 전략을 어떻게 할 것인가
- 동일한 fetch 작업이 연속적으로 수행된다면 어떻게 처리할 것인가

제가 생각한 방법은 위와 같은데 다른 방식의 접근 방법이 있을지 궁금합니다.

**Comment by Cha-Ji** [comment]
공휴일 정도면.. 내부에 저장한 뒤에 개발자들의 수동 업데이트는 어떨까요? ㅋㅋㅋ

**Comment by simeunseok** [comment]
> 공휴일 정도면.. 내부에 저장한 뒤에 개발자들의 수동 업데이트는 어떨까요? ㅋㅋㅋ

이게 제일 베스트일지도...

**Comment by simeunseok** [comment]
모든 공휴일 정보를 받아서 DB에 저장하고
갱신이 필요하면 설정창에 있는 공휴일 갱신 버튼을 통해 갱신하도록 한다.
