### ISSUE TITLE
캘린더 삭제 크래시

### ISSUE THREAD

**Issue by Cha-Ji** [boostcampwm-2021/android01-CalendaRun#321]
- 휴지통 광클하면 꺼짐
<img src="https://user-images.githubusercontent.com/55696672/144018360-ab4b495d-424e-44fc-a20a-ba53a7054c29.gif" width = 350/>

**Comment by simeunseok** [comment]
ㅋㅋ이건 좀 억까아닌가요 ㅠ

**Comment by Cha-Ji** [comment]
ㅋㅋㅋㅋㅋ 저는 강하게 키웁니다
