### ISSUE TITLE
연달력 중복된 슬라이스 적용 시 크래시

### ISSUE THREAD

**Issue by Cha-Ji** [boostcampwm-2021/android01-CalendaRun#349]
## 원인
- 주단위로 item을 그린다.
- 현재 item의 키는 일주일의 첫날(LocalDate)
- 키가 중복되면 크래시가 발생

## 문제
- 뷰가 생성될 때 item의 키값이 LocalDate.now()와 일치할 때까지 스크롤하는 함수가 있다.
- 위 함수 때문에 item 키 값에 날짜정보가 포함되어야 한다.

## 고민
- 키 값에는 날짜 정보가 포함돼야하고 
- 같은 두 주가 키 값이 같아서도 안된다. 
- 어떡하지?

**Comment by simeunseok** [comment]
checkpoint 정책이 그리워지네요...

**Comment by Cha-Ji** [comment]
그땐 이런 오류 없었는데,,

**Comment by shshksh** [comment]
1. 슬라이스 상관 없이 연달력에서 달력의 시작 요일부터 마지막 요일까지를 보여준다.
2. 키값을 autoincrement 같은 걸로 주고 키값과 LocalDate를 매핑하는 map을 추가한다.
    LocalDate 객체가 너무 많아지는게 거슬리면 슬라이스별로 시작 요일의 키값과 LocalDate만 저장하고 필요할때 계산하는 방식으로 해도 될듯?

**Comment by Cha-Ji** [comment]
1번이 가장 솔깃하네요

**Comment by Cha-Ji** [comment]
1번을 해야겠네요. 한 화면에 같은 날짜가 두 개 있는 것 부터가 문제가 많이 생깁니다.
- 기존 로직에서 클릭된 날짜는 LocalDate로 구분하기 때문에 같은 날짜가 두 개 존재하면 두 날짜가 클릭됩니다.
