### ISSUE TITLE
연달력 년도 표시 버그

### ISSUE THREAD

**Issue by PsPLoG** [boostcampwm-2021/android01-CalendaRun#375]
![Screenshot_20211209-183300](https://user-images.githubusercontent.com/13197242/145398458-043a1b75-ce79-4b1d-8f1a-ddafd45fc55e.jpg)
2022년자리에 2021년 표시 
## 진행 상황(option)
- [ ] 연달력 년도 표시 버그

**Comment by Cha-Ji** [comment]
이거 고민을 좀 했었습니다. 최선이라고 생각했는데 이렇게 보니 이상하네요.
일주일이 2021.12.26부터 2022.1.1이면 2021년일까요 2022년일까요?
